/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vectores;

import java.util.Arrays;
import java.util.Random;

/**
 *
 * @author cissanal
 */
public class Permutacion extends javax.swing.JFrame {

    /**
     * Creates new form Permutacion
     */
    public Permutacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonGenerar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonFilas = new javax.swing.JButton();
        jButtonColumnas = new javax.swing.JButton();
        jButtonMostrar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextFieldFila2 = new javax.swing.JTextField();
        jTextFieldFila1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldColumna2 = new javax.swing.JTextField();
        jTextFieldColumna1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Dimension: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel2.setText("X");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jButtonGenerar.setText("Generar");
        jButtonGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 52, 287, 211));

        jButtonFilas.setText("Permutar Filas");
        jButtonFilas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFilasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFilas, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 107, 133, -1));

        jButtonColumnas.setText("Permutar Columnas");
        jButtonColumnas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColumnasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonColumnas, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 206, 133, -1));

        jButtonMostrar.setText("Mostrar");
        jButtonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 240, 133, -1));

        jTextField1.setText("1");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 20, -1));

        jTextField2.setText("1");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 20, -1));

        jTextFieldFila2.setText("1");
        getContentPane().add(jTextFieldFila2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 81, 20, -1));

        jTextFieldFila1.setText("1");
        getContentPane().add(jTextFieldFila1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 55, 20, -1));

        jLabel3.setText("Fila 1");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 58, 44, -1));

        jLabel4.setText("Fila 2");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 84, 44, -1));

        jTextFieldColumna2.setText("1");
        getContentPane().add(jTextFieldColumna2, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 174, 20, -1));

        jTextFieldColumna1.setText("1");
        getContentPane().add(jTextFieldColumna1, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 148, 20, -1));

        jLabel5.setText("Columna 1");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 151, 68, -1));

        jLabel6.setText("Columna 2");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 177, 68, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Random r1 = new Random();
    int ran1 = 0;
    int[][] array1;
    
    
    
    public void permutaFilas(int[][] m, int fila1, int fila2){
        int[][]fila1A=new int[array1.length][array1[0].length];
        int[][]fila2A=new int[array1.length][array1[0].length];
        for (int i = 0; i < array1[0].length; i++) {
            fila1A[fila1][i]=array1[fila1][i];
            fila2A[fila2][i]=array1[fila2][i];
        }
        for (int i = 0; i < array1[0].length; i++) {
            array1[fila1][i]=fila2A[fila2][i];
            array1[fila2][i]=fila1A[fila1][i];
        }
        
    }
    public void permutaColumnas(int[][] m, int columna1, int columna2){
        int[][]columna1A=new int[array1.length][array1[0].length];
        int[][]columna2A=new int[array1.length][array1[0].length];
        for (int i = 0; i < array1.length; i++) {
            columna1A[i][columna1]=array1[i][columna1];
            columna2A[i][columna2]=array1[i][columna2];
        }
        for (int i = 0; i < array1.length; i++) {
            array1[i][columna1]=columna2A[i][columna2];
            array1[i][columna2]=columna1A[i][columna1];
        }
        
    }
    
    
    private void jButtonFilasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFilasActionPerformed
        permutaFilas(array1,Integer.parseInt(this.jTextFieldFila1.getText()),Integer.parseInt(this.jTextFieldFila2.getText()));
    }//GEN-LAST:event_jButtonFilasActionPerformed

    private void jButtonColumnasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColumnasActionPerformed
        permutaColumnas(array1,Integer.parseInt(this.jTextFieldColumna1.getText()),Integer.parseInt(this.jTextFieldColumna2.getText()));
    }//GEN-LAST:event_jButtonColumnasActionPerformed

    private void jButtonGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarActionPerformed
        array1 = new int[Integer.parseInt(this.jTextField1.getText())][Integer.parseInt(this.jTextField2.getText())];
        for (int i = 0; i < array1.length; i++) {
            for (int j = 0; j < array1[0].length; j++) {
                array1[i][j]=(r1.nextInt(100))+1;
            }
        }
        this.jTextArea1.setText(" ");
        for (int i = 0; i < array1.length; i++) {
                this.jTextArea1.append("\n");
            for (int j = 0; j < array1[0].length; j++) {
                this.jTextArea1.append(array1[i][j]+" ");
            }
        }
        
        System.out.println(Arrays.deepToString(array1));
    }//GEN-LAST:event_jButtonGenerarActionPerformed

    private void jButtonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarActionPerformed
        this.jTextArea1.setText(" ");
        for (int i = 0; i < array1.length; i++) {
                this.jTextArea1.append("\n");
            for (int j = 0; j < array1[0].length; j++) {
                this.jTextArea1.append(array1[i][j]+" ");
            }
        }
    }//GEN-LAST:event_jButtonMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Permutacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Permutacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Permutacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Permutacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Permutacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonColumnas;
    private javax.swing.JButton jButtonFilas;
    private javax.swing.JButton jButtonGenerar;
    private javax.swing.JButton jButtonMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFieldColumna1;
    private javax.swing.JTextField jTextFieldColumna2;
    private javax.swing.JTextField jTextFieldFila1;
    private javax.swing.JTextField jTextFieldFila2;
    // End of variables declaration//GEN-END:variables
}
